# Generated by Django 5.2.2 on 2025-06-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotebipagem',
            name='group_user',
            field=models.CharField(default='grupo_padrao', max_length=100),
        ),
        migrations.AddField(
            model_name='lotebipagem',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
