# Generated by Django 5.2.2 on 2025-06-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='nr_caixa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lotebipagem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
