# Generated by Django 5.2.2 on 2025-06-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_caixa_nr_caixa_alter_caixa_id_alter_lotebipagem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bipagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrserie', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bipagem', to='inventario.caixa')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bipagem', to='inventario.lotebipagem')),
            ],
        ),
    ]
