# Generated by Django 5.2.2 on 2025-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_bipagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='unidade',
            field=models.IntegerField(null=True),
        ),
    ]
