# Generated by Django 5.2.2 on 2025-06-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_bipagem_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bipagem',
            name='patrimonio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
