# Generated by Django 5.2.2 on 2025-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_bipagem_modelo_bipagem_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=20),
        ),
    ]
