# Generated by Django 5.2.2 on 2025-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_caixa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('finalizada', 'Finalizada')], default='Iniciada', max_length=20),
        ),
        migrations.AlterField(
            model_name='lotebipagem',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('aguardando validação', 'Aguardando Validação')], default='Aberto', max_length=20),
        ),
    ]
