# Generated by Django 5.2.2 on 2025-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_caixa_status_alter_lotebipagem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotebipagem',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('aguardando validação', 'Aguardando Validação'), ('cancelado', 'Cancelado')], default='Aberto', max_length=20),
        ),
    ]
