# Generated by Django 5.2.2 on 2025-06-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0011_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotebipagem',
            name='group_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='lotebipagem',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('aguardando validação', 'Aguardando Validação'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
