# Generated by Django 5.2.2 on 2025-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_lotebipagem_group_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotebipagem',
            name='group_user',
            field=models.CharField(default='grupo_padrao', max_length=100),
        ),
    ]
