# Generated by Django 5.2.2 on 2025-06-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0015_lotebipagem_group_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotebipagem',
            name='group_user_fk',
        ),
        migrations.AlterField(
            model_name='lotebipagem',
            name='group_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
