# Generated by Django 5.2.2 on 2025-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_lotebipagem_group_user_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotebipagem',
            name='numero_lote',
            field=models.IntegerField(default=1),
        ),
    ]
