# Generated by Django 5.2.2 on 2025-06-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0018_lotebipagem_numero_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoAtendimentoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to='auth.group')),
            ],
        ),
    ]
