# Generated by Django 5.2.2 on 2025-06-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_inventariodadosimportados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotebipagem',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('aguardando validação', 'Aguardando Validação'), ('invalidado', 'Invalidado')], default='Aberto', max_length=20),
        ),
    ]
