# Generated by Django 5.2.2 on 2025-07-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_alter_lotebipagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipagem',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
